const RECURSION_PROBLEMS = [
  {
    "id": "factorial",
    "title": "Factorial",
    "category": "Recursion & Backtracking",
    "difficulty": "Easy",
    "tags": [
      "recursion",
      "math"
    ],
    "description": "Write `factorial(n)` computing `n!` recursively. `factorial(0)` is `1`.",
    "functionName": "factorial",
    "starterCode": "function factorial(n) {\n  \n}",
    "testCases": [
      {
        "args": [
          0
        ],
        "expected": 1
      },
      {
        "args": [
          1
        ],
        "expected": 1
      },
      {
        "args": [
          5
        ],
        "expected": 120
      },
      {
        "args": [
          10
        ],
        "expected": 3628800
      }
    ]
  },
  {
    "id": "fibonacci-recursive",
    "title": "Fibonacci (Recursive)",
    "category": "Recursion & Backtracking",
    "difficulty": "Easy",
    "tags": [
      "recursion",
      "math"
    ],
    "description": "Write `fibonacci(n)` returning the `n`-th Fibonacci number using recursion, with `fibonacci(0) = 0` and `fibonacci(1) = 1`.",
    "functionName": "fibonacci",
    "starterCode": "function fibonacci(n) {\n  \n}",
    "testCases": [
      {
        "args": [
          0
        ],
        "expected": 0
      },
      {
        "args": [
          1
        ],
        "expected": 1
      },
      {
        "args": [
          10
        ],
        "expected": 55
      },
      {
        "args": [
          15
        ],
        "expected": 610
      }
    ]
  },
  {
    "id": "power-function",
    "title": "Pow(x, n)",
    "category": "Recursion & Backtracking",
    "difficulty": "Medium",
    "tags": [
      "recursion",
      "math"
    ],
    "description": "Write `myPow(x, n)` computing `x` raised to the integer power `n` (n can be negative). Round the result to 5 decimal places to avoid floating point comparison issues.",
    "functionName": "myPow",
    "starterCode": "function myPow(x, n) {\n  \n}",
    "testCases": [
      {
        "args": [
          2,
          10
        ],
        "expected": 1024
      },
      {
        "args": [
          2.1,
          3
        ],
        "expected": 9.261
      },
      {
        "args": [
          2,
          -2
        ],
        "expected": 0.25
      },
      {
        "args": [
          1,
          100
        ],
        "expected": 1
      }
    ]
  },
  {
    "id": "subsets",
    "title": "Subsets",
    "category": "Recursion & Backtracking",
    "difficulty": "Medium",
    "tags": [
      "backtracking",
      "array"
    ],
    "description": "Write `subsets(nums)` returning all possible subsets (the power set) of `nums` (no duplicates in input). Order: for each of the 2^n subsets, include element `i` if bit `i` is set in the subset's index counting from 0 upward; append subsets in that index order.",
    "functionName": "subsets",
    "starterCode": "function subsets(nums) {\n  \n}",
    "testCases": [
      {
        "args": [
          [
            1,
            2,
            3
          ]
        ],
        "expected": [
          [],
          [
            1
          ],
          [
            2
          ],
          [
            1,
            2
          ],
          [
            3
          ],
          [
            1,
            3
          ],
          [
            2,
            3
          ],
          [
            1,
            2,
            3
          ]
        ]
      },
      {
        "args": [
          [
            0
          ]
        ],
        "expected": [
          [],
          [
            0
          ]
        ]
      },
      {
        "args": [
          []
        ],
        "expected": [
          []
        ]
      },
      {
        "args": [
          [
            1,
            2
          ]
        ],
        "expected": [
          [],
          [
            1
          ],
          [
            2
          ],
          [
            1,
            2
          ]
        ]
      }
    ]
  },
  {
    "id": "permutations",
    "title": "Permutations",
    "category": "Recursion & Backtracking",
    "difficulty": "Medium",
    "tags": [
      "backtracking",
      "array"
    ],
    "description": "Write `permute(nums)` returning all permutations of the distinct integers in `nums`, generated by always picking the next unused element in ascending index order at each recursive step (standard backtracking order).",
    "functionName": "permute",
    "starterCode": "function permute(nums) {\n  \n}",
    "testCases": [
      {
        "args": [
          [
            1,
            2,
            3
          ]
        ],
        "expected": [
          [
            1,
            2,
            3
          ],
          [
            1,
            3,
            2
          ],
          [
            2,
            1,
            3
          ],
          [
            2,
            3,
            1
          ],
          [
            3,
            1,
            2
          ],
          [
            3,
            2,
            1
          ]
        ]
      },
      {
        "args": [
          [
            0,
            1
          ]
        ],
        "expected": [
          [
            0,
            1
          ],
          [
            1,
            0
          ]
        ]
      },
      {
        "args": [
          [
            1
          ]
        ],
        "expected": [
          [
            1
          ]
        ]
      },
      {
        "args": [
          []
        ],
        "expected": [
          []
        ]
      }
    ]
  },
  {
    "id": "combination-sum",
    "title": "Combination Sum",
    "category": "Recursion & Backtracking",
    "difficulty": "Medium",
    "tags": [
      "backtracking"
    ],
    "description": "Write `combinationSum(candidates, target)` returning all unique combinations (candidates may repeat within a combination) of `candidates` that sum to `target`. Explore candidates in the given order, only using each at index ≥ the previous pick's index (so no duplicate combinations); each combination sorted the same way `candidates` is given.",
    "functionName": "combinationSum",
    "starterCode": "function combinationSum(candidates, target) {\n  \n}",
    "testCases": [
      {
        "args": [
          [
            2,
            3,
            6,
            7
          ],
          7
        ],
        "expected": [
          [
            2,
            2,
            3
          ],
          [
            7
          ]
        ]
      },
      {
        "args": [
          [
            2,
            3,
            5
          ],
          8
        ],
        "expected": [
          [
            2,
            2,
            2,
            2
          ],
          [
            2,
            3,
            3
          ],
          [
            3,
            5
          ]
        ]
      },
      {
        "args": [
          [
            2
          ],
          1
        ],
        "expected": []
      },
      {
        "args": [
          [
            1
          ],
          2
        ],
        "expected": [
          [
            1,
            1
          ]
        ]
      }
    ]
  },
  {
    "id": "generate-parentheses",
    "title": "Generate Parentheses",
    "category": "Recursion & Backtracking",
    "difficulty": "Medium",
    "tags": [
      "backtracking",
      "string"
    ],
    "description": "Write `generateParenthesis(n)` returning all combinations of `n` pairs of well-formed parentheses, generated by trying to place an open paren before a close paren at each step (standard order).",
    "functionName": "generateParenthesis",
    "starterCode": "function generateParenthesis(n) {\n  \n}",
    "testCases": [
      {
        "args": [
          3
        ],
        "expected": [
          "((()))",
          "(()())",
          "(())()",
          "()(())",
          "()()()"
        ]
      },
      {
        "args": [
          1
        ],
        "expected": [
          "()"
        ]
      },
      {
        "args": [
          2
        ],
        "expected": [
          "(())",
          "()()"
        ]
      },
      {
        "args": [
          4
        ],
        "expected": [
          "(((())))",
          "((()()))",
          "((())())",
          "((()))()",
          "(()(()))",
          "(()()())",
          "(()())()",
          "(())(())",
          "(())()()",
          "()((()))",
          "()(()())",
          "()(())()",
          "()()(())",
          "()()()()"
        ]
      }
    ]
  },
  {
    "id": "digit-sum-recursive",
    "title": "Digital Root (Recursive Digit Sum)",
    "category": "Recursion & Backtracking",
    "difficulty": "Easy",
    "tags": [
      "recursion",
      "math"
    ],
    "description": "Write `digitSum(n)` that repeatedly (recursively) sums the digits of `n` until a single digit remains, and returns that digit.",
    "functionName": "digitSum",
    "starterCode": "function digitSum(n) {\n  \n}",
    "testCases": [
      {
        "args": [
          38
        ],
        "expected": 2
      },
      {
        "args": [
          0
        ],
        "expected": 0
      },
      {
        "args": [
          9875
        ],
        "expected": 2
      },
      {
        "args": [
          123456789
        ],
        "expected": 9
      }
    ]
  }
];

export default RECURSION_PROBLEMS;
